name: snowp
main: com.svo.snowp.Snowp
version: 1.0.2-ALPHA
api-version: 1.21
has-open-classloader: false
commands:
  debugsnow:
    description: Открывает Debug Snow GUI
    usage: /debugsnow
    permission: op
    
